---
title: "Pregunta 1 - Trabajo Final"
author: "Diego Uriarte"
date: "11 de junio de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
rm(list = ls())
```

## Cargamos la data

```{r}
data <- read.csv("../Data BCR/Trimestrales-20180612-094753.csv")

colnames(data) <- c("Fecha1", "Consumo Privado", "Consumo Público", "Inversión Privada", "Inversión Pública", "Exportaciones", "Importaciones", "PBI")
data <- data[-1,]
#removemos último elemento
data <- data[-154,]
#creamos vector de fechas
sec_date <- data.frame(seq(as.Date("1980/1/1"), as.Date("2018/1/1"), by = "quarter"))
colnames(sec_date) <- "Fecha"
data <- cbind(data, sec_date)
orden_datos <- c("PBI", "Consumo Privado", "Consumo Público", "Inversión Privada", "Inversión Pública", "Exportaciones", "Importaciones")
#nuevo df con datos ordenos
data <- data[c("Fecha", orden_datos )]
row.names(data) <- NULL
#convertimos de fctr a double
function2 <- function(x) as.numeric(levels(x))[as.integer(x)]
data[, orden_datos] <- sapply(data[, orden_datos], function2 )


```

```{r}
data <- data %>%
  mutate(lnPBI = log(PBI))
```



Graficamos la data tal cual:

```{r}
library(ggplot2)
library(reshape2)
library(mFilter)
ggplot(data,aes(x=Fecha,y=lnPBI)) + geom_line(size=.5) + theme_classic() + labs(title="Log PBI Perú")
```

```{r}
plot.cycles <- function(d,t) {
ggplot(g,aes(x=Fecha,y=value,linetype=variable)) +
geom_hline(yintercept=0,colour="grey80") + # Create a horizontal line with value 0
geom_line(size=.5) + # Create line with series and specify its thickness
labs(x="Fecha",y="",title=t,linetype="Legend:") + # Title of the legend
coord_cartesian(xlim=c(min(g[,1]),max(g[,1])),expand=FALSE) + # Set displayed area
guides(linetype=guide_legend()) + # Set the variables contained in the legend
theme(legend.position="bottom", # Position of the legend
legend.key=element_rect(fill="white"), # Set background of the legend keys
panel.background = element_rect(fill = "white"), # Set background of the graph
axis.line=element_line(size=.3,colour="black"), # Set the size and colour of the axes
axis.text=element_text(colour="black"), # Set the colour of the axes text
panel.grid=element_blank()) # Set grid lines off
}
```


Aplicamos filtro Baxter-King

```{r}
hp <- hpfilter(data[c("lnPBI")],freq=1600)$cycle
bk <- bkfilter(data[,c("lnPBI")],pl=6,pu=32,nfix=12)$cycle[,1] # Apply filter and obtain cycle component
 
# Plot
data <- cbind(data,data.frame("Baxter.King"=bk,"Hodrick.Prescott" =hp))
g <- melt(data[,c("Fecha", "Baxter.King", "Hodrick.Prescott")],id.vars="Fecha",na.rm=TRUE)

plot.cycles(g,"Baxter King vs. Hodrick Prescott")
```

No se aprecia muy bien, intentemos graficando el valor cíclico respecto al tendencial

```{r}
hp_trend_pbi <- hpfilter(data[c("lnPBI")],freq=1600)$trend
colnames(hp_trend_pbi) <- "lnPBI_tend_HP"
bk_trend_pbi <- bkfilter(data[,c("lnPBI")],pl=6,pu=32,nfix=12)$trend
colnames(bk_trend_pbi) <- "lnPBI_tend_BK"
data <- cbind(data,data.frame(bk_trend_pbi,hp_trend_pbi))
data <- data %>%
  mutate(perc_pbi_hp = Hodrick.Prescott/abs(hp_trend_pbi)*100, perc_pbi_bk = Baxter.King/abs(bk_trend_pbi))

g <- melt(data[,c("Fecha", "perc_pbi_hp", "perc_pbi_bk")],id.vars="Fecha",na.rm=TRUE)
plot.cycles(g,"Comparación")

```

